{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.ddms",
    "module": "ddmlib",
    "version": "27.2.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "jlvi3e3hkzflnogl672y5wgd2m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "27.2.0-rc01"
          }
        },
        {
          "group": "net.sf.kxml",
          "module": "kxml2",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "ddmlib-27.2.0-rc01.jar",
          "url": "ddmlib-27.2.0-rc01.jar",
          "size": 483826,
          "sha512": "52b5d8077dae0a84d53b9ee9e019d74492d6b8b060278a7a34ed7d0a26705be7732d371c5ac2277188356520d567ce78f2133336114b6cd6238a8d8272a29613",
          "sha256": "c8c484ed953aae25c35ffb11868390489a1dc8a19104bdf95c217903ac39455d",
          "sha1": "963d100811d1048b3b5c41840b025ad0663c26eb",
          "md5": "b5ec7f23e8edd801a2d8af11c8b7d0e6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "27.2.0-rc01"
          }
        },
        {
          "group": "net.sf.kxml",
          "module": "kxml2",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "ddmlib-27.2.0-rc01.jar",
          "url": "ddmlib-27.2.0-rc01.jar",
          "size": 483826,
          "sha512": "52b5d8077dae0a84d53b9ee9e019d74492d6b8b060278a7a34ed7d0a26705be7732d371c5ac2277188356520d567ce78f2133336114b6cd6238a8d8272a29613",
          "sha256": "c8c484ed953aae25c35ffb11868390489a1dc8a19104bdf95c217903ac39455d",
          "sha1": "963d100811d1048b3b5c41840b025ad0663c26eb",
          "md5": "b5ec7f23e8edd801a2d8af11c8b7d0e6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ddmlib-27.2.0-rc01-javadoc.jar",
          "url": "ddmlib-27.2.0-rc01-javadoc.jar",
          "size": 556211,
          "sha512": "0ffa266f60ce81e0dd6feda3f3e4732760e2ebfe8ae711df224da3f41e618a7c9a505303ab5268cfc8fa9c21fcad601d9d4bf791c7d5f5279e598918aaac446c",
          "sha256": "d2f47557f2a5f63c608978926b07e0a70d2959d3cce079afe81038997fd18d2d",
          "sha1": "478f8f2fa5b5a9080cb1d954fdd5357956cc1d79",
          "md5": "96eb7a0c784eb318a11ae88d1948d8ff"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ddmlib-27.2.0-rc01-sources.jar",
          "url": "ddmlib-27.2.0-rc01-sources.jar",
          "size": 607992,
          "sha512": "3d9b43b853e8001199d7afc3e22c18c4e6b7249dd9abed2ca1faa3fd9830a661750d4103b8ee67d30de4f76a079d7ac2ad5f11287dfe6d7313ed15aa501630d5",
          "sha256": "e739e623861180ecf8c1e38c36d83ab1804497ac4cfd5e247823ef02842655ca",
          "sha1": "99c584969cce82d5fd30ed1b9df059eec813b278",
          "md5": "35bc44a761f5ed9ed8c8990a988ef091"
        }
      ]
    }
  ]
}
