{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "apkzlib",
    "version": "4.2.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "jlvi3e3hkzflnogl672y5wgd2m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.56"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.56"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "4.2.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "apkzlib-4.2.0-rc01.jar",
          "url": "apkzlib-4.2.0-rc01.jar",
          "size": 204415,
          "sha512": "f3fab2d8af85227129221a182616613db2332a6f22d96c44fe85baec6f8b7107bb2158c2fb61b2c9a5b7f25b3f82ccd747774506f6968c0b12b7ce7d10105a3e",
          "sha256": "a3ffc6bbf0818de180ac9db238787d45a48b0641fa5721444b62f9162fa47166",
          "sha1": "a97cd8647b31e5c3fa1f8403a64075fe60f06144",
          "md5": "e64a5f1b5734062e5ef7a305ac486a1c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.56"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.56"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "4.2.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "apkzlib-4.2.0-rc01.jar",
          "url": "apkzlib-4.2.0-rc01.jar",
          "size": 204415,
          "sha512": "f3fab2d8af85227129221a182616613db2332a6f22d96c44fe85baec6f8b7107bb2158c2fb61b2c9a5b7f25b3f82ccd747774506f6968c0b12b7ce7d10105a3e",
          "sha256": "a3ffc6bbf0818de180ac9db238787d45a48b0641fa5721444b62f9162fa47166",
          "sha1": "a97cd8647b31e5c3fa1f8403a64075fe60f06144",
          "md5": "e64a5f1b5734062e5ef7a305ac486a1c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "apkzlib-4.2.0-rc01-javadoc.jar",
          "url": "apkzlib-4.2.0-rc01-javadoc.jar",
          "size": 300653,
          "sha512": "70a8a3fdb44b2f6c6774822dc30dac6aeb657d2333ecf461411df3d9564df97c231ee008817d74d100037179dec732afd0eb633cbd71ca906846677941825c70",
          "sha256": "c801435bcb2c3f539b17c793ded5f9e4a92059c4605ee5df255f52241688f3ca",
          "sha1": "1dab3e9c9f85f558f9d4d0a657dac9b09df06872",
          "md5": "d34cbca4784b1c2dfd0660961c75050e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "apkzlib-4.2.0-rc01-sources.jar",
          "url": "apkzlib-4.2.0-rc01-sources.jar",
          "size": 175631,
          "sha512": "4bb88167c8478145c8513520a6b3750700fe9854af4fb9b758285f2416e69f59e0b46e71ecf8c6753e2dd9b29209b25b48b0638b4739ea0d62d2385b4659d6a6",
          "sha256": "16495ed7e383c2965a4bf8cc079a107da9bb381a233bf2996f23b2fcd6fc10f3",
          "sha1": "3f5c03ef5379e523081d07af527caa4ae5bd84b8",
          "md5": "fa1591e0a5dd705dfd365bb6b6c9175f"
        }
      ]
    }
  ]
}
